---
deployment:
  tasks:
    # Renomear index-cpanel.html para index.html
    - /bin/cp index-cpanel.html index.html
    
    # Criar arquivo de log
    - echo "Deploy realizado em $(date)" >> deploy.log
    
    # Definir permissões corretas
    - /bin/chmod 644 index.html
    - /bin/chmod 644 styles.css
    - /bin/chmod 644 script.js
