---
deployment:
  tasks:
    # Renomear index-cpanel.html para index.html
    - /bin/mv -f index-cpanel.html index.html
    
    # Definir permissões corretas
    - /bin/chmod 644 index.html
    - /bin/chmod 644 styles.css
    - /bin/chmod 644 script.js
