---
deployment:
  tasks:
    # Definir permissões corretas para o diretório e arquivos
    - export DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/index.html
    - /bin/chmod 644 $DEPLOYPATH/styles.css
    - /bin/chmod 644 $DEPLOYPATH/script.js
